/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Controller;

import Controller.Main.MainController;
import Services.ConnectDatabase;
import Services.Services;

public class App {

    public static void main(String[] args) {
//        new Auth_Controller();
          new ConnectDBController();
//        var connectDB = new ConnectDatabase();
//        connectDB.connectDatabase("192.168.30.103", "sa", "123");        
//        new MainController();
    }
}
